services:

  app:
    image: ict-api-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: ict-api-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ict-api
      - database

  nginx:
    image: ict-api-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: ict-api-nginx
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - ict-api
      - proxy

networks:
  ict-api:
    driver: bridge
  proxy:
    external: true
  database:
    external: true
